app:
  build: ./code
  command: cat
  stdin_open: true
fpm:
  build: ./php-fpm
  tty: true
  stdin_open: true
  volumes_from:
    - app
  labels:
    io.rancher.sidekicks: app
nginx:
  build: ./nginx
  volumes_from:
    - app
    - fpm
  links:
    - fpm
  ports:
    - 9999:80
  labels:
    io.rancher.sidekicks: app, fpm