version: '2'
services:
  code:
    build: ./code
    volumes:
      - ./code:/var/www/html
  php:
    build: ./php-fpm
    volumes_from:
      - code
  nginx:
    build: ./nginx
    volumes_from:
      - code
    links:
      - php:fpm
    ports:
      - 80:80